### ISSUE TITLE
調整訊息回覆方式

### ISSUE THREAD

**Issue by eboy3575** [mesak/laravel-linebot#1]
詢問如何將一次回覆回傳一則訊息調整為

- 可以回覆多則訊息
- 可回覆除text, flex 以外的所有型態的訊息。

謝謝

**Comment by mesak** [comment]
> * 可以回覆多則訊息

你好，回覆多則訊息是要計算數量的，超過要收費，如果確定要回覆多內容的話應該是要根據對方的 uid 進行發送訊息

> * 可回覆除text, flex 以外的所有型態的訊息。

這個不是很懂， LINE 預設就是 給 text 跟 flex ，如果要回應其他訊息 應該是 繼承 BaseAction  去呼叫

**Comment by eboy3575** [comment]
你好：
在 replyMessage 時一次最多可以回復五則訊息，且可以回復以下類型的訊息給使用者：
- [Text message](https://developers.line.biz/en/docs/messaging-api/message-types/#text-messages)
- [Sticker message](https://developers.line.biz/en/docs/messaging-api/message-types/#sticker-messages)
- [Image message](https://developers.line.biz/en/docs/messaging-api/message-types/#image-messages)
- [Video message](https://developers.line.biz/en/docs/messaging-api/message-types/#video-messages)
- [Audio message](https://developers.line.biz/en/docs/messaging-api/message-types/#audio-messages)
- [Location message](https://developers.line.biz/en/docs/messaging-api/message-types/#location-messages)
- [Imagemap message](https://developers.line.biz/en/docs/messaging-api/message-types/#imagemap-messages)
- [Template message](https://developers.line.biz/en/docs/messaging-api/message-types/#template-messages)
- [Flex Message](https://developers.line.biz/en/docs/messaging-api/message-types/#flex-messages)

在請求 API 時會以下列方式呈現：
```
curl -v -X POST https://api.line.me/v2/bot/message/reply \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer {channel access token}' \
-d '{
    "replyToken":"nHuyWiB7yP5Zw52FIkcQobQuGDXCTA",
    "messages":[
        {
            "type":"text",
            "text":"Hello, user"
        },
        {
            "type":"text",
            "text":"May I help you?"
        }
    ]
}'
```

<img width="904" alt="image" src="https://github.com/mesak/laravel-linebot/assets/18606652/abb6afe1-6cc5-4177-8a30-7c3e612dffd9">

**Comment by mesak** [comment]
> 你好： 在 replyMessage 時一次最多可以回復五則訊息，且可以回復以下類型的訊息給使用者：

好的，Bot 最終是走 `$bot->execute($type, $target, $action->getMessage());`

所以是可以建立  $action 給予多個 MessageClass ，因為最終呼叫也是使用 LINE 本身提供的 PHP SDK

建議建立一個 MultipleActions.php

```

namespace App\LineBot\Actions;

use LINE\LINEBot\MessageBuilder\TextMessageBuilder;
use LINE\LINEBot\MessageBuilder\MultiMessageBuilder;

class MultipleActions extends \Mesak\LineBot\Actions\BaseAction
{

  public function __construct($text)
  {
    $this->message = new MultiMessageBuilder();


    $textClass1  =  new TextMessageBuilder($text);
    $textClass2  =  new TextMessageBuilder($text);

   $this->message->add($textClass1);
   $this->message->add($textClass2);
  }
  
}
```
建立這個  Action 去讓 Listener 回傳，至於怎麼回傳....  這個套件我暫停維護了，我覺得使用 Event Listener 回傳回應會有點久，所以還沒時間改善他，有點繞過多了...
